---

# This does not work as of 2017-04-25 / ansible 2.2.2.0
#- include_role: name=mit.zabbix-agent.common task_from=get-zabbix-agent-path
- include_tasks: ../../mit.zabbix-agent.common/tasks/get-zabbix-agent-path.yml

- name: Copy zabbix elasticsearch script
  copy: src=zabbix-elasticsearch dest=/usr/local/bin/zabbix-elasticsearch mode=0755
  become: yes

- name: Add zabbix-agent configuration file
  copy: src=local-userparameter_elasticsearch.conf dest={{ zabbix_agent_conf_dir }} mode=0644
  notify: Restart zabbix-agent
  become: yes

