---

# We now include mit.zabbix-agent.common via dependency in meta/main.yml
# This provides handlers like "Restart zabbix-agent" and vars like "zabbix_agent_conf_dir"

- name: Copy zabbix elasticsearch script
  copy: src=zabbix-elasticsearch dest=/usr/local/bin/zabbix-elasticsearch mode=0755
  become: yes

- name: Add zabbix-agent configuration file
  copy: src=local-userparameter_elasticsearch.conf dest={{ zabbix_agent_conf_dir }} mode=0644
  notify: Restart zabbix-agent
  become: yes

